# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf78937e1345277f5b470f2c159cc3430a900fe66f1b5ae8e652ad15cfd30ddd0fb09e74c30a294a183706cff048f24f4afcad3f3a05e3df71e56cf18bda51d2

test:
  secret_key_base: 9b59d7fd3d4cf67de69b27f862b180a6bd88ab2b359bb7cf9e0d299b44ff311816541f9712b8dfd3ae8d445b7a6dd50b16b187239b40f7cbbe088f8ae79dc5ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
